name: online_admission
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  loading_overlay: ^0.3.0
  block_input: ^1.2.7
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.2
  pdfx: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/